// Generated by gencpp from file servicio_suma/AddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef SERVICIO_SUMA_MESSAGE_ADDTWOINTSRESPONSE_H
#define SERVICIO_SUMA_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servicio_suma
{
template <class ContainerAllocator>
struct AddTwoIntsResponse_
{
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
    : sum(0.0)  {
    }
  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef double _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsResponse_

typedef ::servicio_suma::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::servicio_suma::AddTwoIntsResponse > AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::servicio_suma::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servicio_suma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "981739b4699a7cf1b15030371beffb96";
  }

  static const char* value(const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x981739b4699a7cf1ULL;
  static const uint64_t static_value2 = 0xb15030371beffb96ULL;
};

template<class ContainerAllocator>
struct DataType< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servicio_suma/AddTwoIntsResponse";
  }

  static const char* value(const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 sum\n"
"\n"
;
  }

  static const char* value(const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servicio_suma::AddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<double>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICIO_SUMA_MESSAGE_ADDTWOINTSRESPONSE_H
