; Auto-generated. Do not edit!


(cl:in-package mi_accion-msg)


;//! \htmlinclude ejFibonacciFeedback.msg.html

(cl:defclass <ejFibonacciFeedback> (roslisp-msg-protocol:ros-message)
  ((secuencia_actual
    :reader secuencia_actual
    :initarg :secuencia_actual
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ejFibonacciFeedback (<ejFibonacciFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ejFibonacciFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ejFibonacciFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mi_accion-msg:<ejFibonacciFeedback> is deprecated: use mi_accion-msg:ejFibonacciFeedback instead.")))

(cl:ensure-generic-function 'secuencia_actual-val :lambda-list '(m))
(cl:defmethod secuencia_actual-val ((m <ejFibonacciFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mi_accion-msg:secuencia_actual-val is deprecated.  Use mi_accion-msg:secuencia_actual instead.")
  (secuencia_actual m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ejFibonacciFeedback>) ostream)
  "Serializes a message object of type '<ejFibonacciFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'secuencia_actual))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'secuencia_actual))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ejFibonacciFeedback>) istream)
  "Deserializes a message object of type '<ejFibonacciFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'secuencia_actual) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'secuencia_actual)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ejFibonacciFeedback>)))
  "Returns string type for a message object of type '<ejFibonacciFeedback>"
  "mi_accion/ejFibonacciFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ejFibonacciFeedback)))
  "Returns string type for a message object of type 'ejFibonacciFeedback"
  "mi_accion/ejFibonacciFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ejFibonacciFeedback>)))
  "Returns md5sum for a message object of type '<ejFibonacciFeedback>"
  "54830236484f66854ffa994e44f37596")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ejFibonacciFeedback)))
  "Returns md5sum for a message object of type 'ejFibonacciFeedback"
  "54830236484f66854ffa994e44f37596")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ejFibonacciFeedback>)))
  "Returns full string definition for message of type '<ejFibonacciFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] secuencia_actual~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ejFibonacciFeedback)))
  "Returns full string definition for message of type 'ejFibonacciFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] secuencia_actual~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ejFibonacciFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'secuencia_actual) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ejFibonacciFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ejFibonacciFeedback
    (cl:cons ':secuencia_actual (secuencia_actual msg))
))
